import { FC } from "react";

 
const Performance: FC = () => {
  return (
    <div>
      <h1>Performance Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem, voluptate sequi distinctio cupiditate ullam eos omnis magnam similique qui porro provident excepturi nisi expedita nostrum earum rem perspiciatis, minus dolorem non, eligendi dolore. Eaque, debitis. Veniam possimus voluptatem iste libero minus itaque, vel ex animi minima. Mollitia aliquid quaerat sapiente, soluta nobis tempora. Nam culpa voluptates id nobis asperiores nulla commodi cumque qui inventore voluptatibus? Numquam amet officia laborum itaque inventore soluta rerum ut ex dolorum quo quae earum nesciunt debitis minima laudantium recusandae provident sapiente repellat, cupiditate incidunt iure nemo vitae eius quasi! Saepe deserunt doloribus quidem nostrum, praesentium quo fugiat aliquam qui et perferendis veniam officia ea error alias eos quas explicabo, vero corrupti sint molestias blanditiis facere! Officia error ipsa perspiciatis ipsam quis autem debitis temporibus, dolore quam aliquid reiciendis nobis neque molestiae? Amet illo voluptatum maiores, placeat cumque architecto natus fugit asperiores ratione saepe non ab nobis nostrum esse omnis numquam pariatur doloremque? Aperiam maiores voluptatum tempora consectetur, nobis accusamus consequatur animi, facilis optio recusandae blanditiis. Totam et reprehenderit dignissimos saepe ipsa! Reprehenderit nam laborum omnis esse ratione aliquid doloremque vero? Ullam velit magni explicabo corrupti odio sed optio cumque eveniet, accusamus veritatis repellendus numquam necessitatibus inventore commodi minus distinctio veniam exercitationem cupiditate odit illo qui. Deleniti aliquid ratione id facere sint alias, quidem odio ab dolorem adipisci quaerat facilis numquam unde quisquam eaque, repellat maiores. Veritatis consequatur, aut iure facilis veniam illum nobis unde aperiam repellat, labore dolores vitae similique laudantium exercitationem quibusdam? Fugiat magni velit beatae illo veniam. Aspernatur voluptatum molestias, maiores adipisci officiis nulla eaque obcaecati, esse harum, reiciendis delectus saepe. Velit optio delectus officiis, rem perspiciatis aperiam possimus iure dignissimos, sit eum repellendus, consequuntur reprehenderit obcaecati similique consectetur maxime commodi maiores aut. Consequuntur nam aliquam aut, animi enim omnis cum nulla alias!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, corrupti quo. Rem possimus nisi ratione suscipit, quidem nostrum quam laborum, vitae sunt in aut perferendis dolore cum quaerat animi ad odit repellendus doloribus eligendi atque sed vel dolorem. Doloremque, magnam! Soluta eaque dolore reprehenderit tenetur, ipsum nostrum! Est quas tempore molestiae cupiditate provident quos voluptatum non itaque! Dolorum laborum illum laboriosam sapiente quisquam mollitia veniam ipsum! Adipisci laborum sit quas harum accusantium odio fuga eum perspiciatis? Doloribus alias enim vero dolores, qui exercitationem animi laborum. Similique eligendi neque cupiditate quaerat error libero labore cum ipsum iste quidem, tenetur corporis ullam, quas odit consequatur nobis aut, magni sapiente. Placeat reiciendis, quia quaerat, labore at quam dolor similique magni dignissimos dolores ut reprehenderit debitis illo! Magnam nostrum, ad illo eligendi, a neque fugiat, molestiae nobis suscipit iste autem ullam eveniet harum nihil distinctio. Omnis beatae minima magnam natus, cum maiores nesciunt dolore consequuntur consequatur veritatis recusandae, inventore, vitae culpa qui corrupti expedita modi. Quos explicabo vitae totam ipsa rem reiciendis rerum aperiam aliquam nisi ipsam quia maiores quidem, nesciunt hic tempora veniam necessitatibus placeat corporis ad, deserunt ut sunt! Dicta laborum cumque sunt, hic, amet consequuntur perferendis repellendus odit dolore, nihil molestias!</p>
    </div>
    
  );
}
 
export default Performance;